/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sim_jnative_SimulatorConnector */

#ifndef _Included_sim_jnative_SimulatorConnector
#define _Included_sim_jnative_SimulatorConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sim_jnative_SimulatorConnector
 * Method:    initSimulator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sim_jnative_SimulatorConnector_initSimulator
  (JNIEnv *, jobject);

/*
 * Class:     sim_jnative_SimulatorConnector
 * Method:    runTCSimulatior
 * Signature: (Ljava/lang/String;[FFIII)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_sim_jnative_SimulatorConnector_runTCSimulatior
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
