/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sim_jnative_PSConnector */

#ifndef _Included_sim_jnative_PSConnector
#define _Included_sim_jnative_PSConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sim_jnative_PSConnector
 * Method:    initSimulator
 * Signature: (I)I
 */
JNIEXPORT jlong JNICALL Java_sim_jnative_PSConnector_initSimulator
  (JNIEnv *, jobject, jint);

/*
 * Class:     sim_jnative_PSConnector
 * Method:    runTCSimulatior
 * Signature: (IF[FFIII)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_sim_jnative_PSConnector_runTCSimulatior
(JNIEnv *, jobject, jstring, jstring, jstring, jfloat, jobjectArray, jdoubleArray, jfloat, jint, jint, jint, jint, jint, jint, jlong);
 // (JNIEnv *, jobject, jint, jfloat, jobjectArray, jdoubleArray, jfloat, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
