/* soapH.h
   Generated by gSOAP 2.7.15 from timecoursews.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#define soap_write_float(soap, data) ( soap_begin_send(soap) || (soap_serialize_float(soap, data), 0) || soap_put_float(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__OutputResult_format
#define SOAP_TYPE__ns3__OutputResult_format (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__OutputResult_format(struct soap*, enum _ns3__OutputResult_format *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__OutputResult_format(struct soap*, const char*, int, const enum _ns3__OutputResult_format *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns3__OutputResult_format2s(struct soap*, enum _ns3__OutputResult_format);
SOAP_FMAC3 enum _ns3__OutputResult_format * SOAP_FMAC4 soap_in__ns3__OutputResult_format(struct soap*, const char*, enum _ns3__OutputResult_format *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns3__OutputResult_format(struct soap*, const char*, enum _ns3__OutputResult_format *);

#define soap_write__ns3__OutputResult_format(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__OutputResult_format(soap, data), 0) || soap_put__ns3__OutputResult_format(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__OutputResult_format(struct soap*, const enum _ns3__OutputResult_format *, const char*, const char*);

#define soap_read__ns3__OutputResult_format(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__OutputResult_format(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum _ns3__OutputResult_format * SOAP_FMAC4 soap_get__ns3__OutputResult_format(struct soap*, enum _ns3__OutputResult_format *, const char*, const char*);

#ifndef SOAP_TYPE__ns2__DeterministicParameters_outputFormat
#define SOAP_TYPE__ns2__DeterministicParameters_outputFormat (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns2__DeterministicParameters_outputFormat(struct soap*, enum _ns2__DeterministicParameters_outputFormat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__DeterministicParameters_outputFormat(struct soap*, const char*, int, const enum _ns2__DeterministicParameters_outputFormat *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns2__DeterministicParameters_outputFormat2s(struct soap*, enum _ns2__DeterministicParameters_outputFormat);
SOAP_FMAC3 enum _ns2__DeterministicParameters_outputFormat * SOAP_FMAC4 soap_in__ns2__DeterministicParameters_outputFormat(struct soap*, const char*, enum _ns2__DeterministicParameters_outputFormat *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns2__DeterministicParameters_outputFormat(struct soap*, const char*, enum _ns2__DeterministicParameters_outputFormat *);

#define soap_write__ns2__DeterministicParameters_outputFormat(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns2__DeterministicParameters_outputFormat(soap, data), 0) || soap_put__ns2__DeterministicParameters_outputFormat(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns2__DeterministicParameters_outputFormat(struct soap*, const enum _ns2__DeterministicParameters_outputFormat *, const char*, const char*);

#define soap_read__ns2__DeterministicParameters_outputFormat(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__DeterministicParameters_outputFormat(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum _ns2__DeterministicParameters_outputFormat * SOAP_FMAC4 soap_get__ns2__DeterministicParameters_outputFormat(struct soap*, enum _ns2__DeterministicParameters_outputFormat *, const char*, const char*);

#ifndef SOAP_TYPE__ns2__DeterministicParameters_inputFormat
#define SOAP_TYPE__ns2__DeterministicParameters_inputFormat (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns2__DeterministicParameters_inputFormat(struct soap*, enum _ns2__DeterministicParameters_inputFormat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__DeterministicParameters_inputFormat(struct soap*, const char*, int, const enum _ns2__DeterministicParameters_inputFormat *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns2__DeterministicParameters_inputFormat2s(struct soap*, enum _ns2__DeterministicParameters_inputFormat);
SOAP_FMAC3 enum _ns2__DeterministicParameters_inputFormat * SOAP_FMAC4 soap_in__ns2__DeterministicParameters_inputFormat(struct soap*, const char*, enum _ns2__DeterministicParameters_inputFormat *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns2__DeterministicParameters_inputFormat(struct soap*, const char*, enum _ns2__DeterministicParameters_inputFormat *);

#define soap_write__ns2__DeterministicParameters_inputFormat(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns2__DeterministicParameters_inputFormat(soap, data), 0) || soap_put__ns2__DeterministicParameters_inputFormat(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns2__DeterministicParameters_inputFormat(struct soap*, const enum _ns2__DeterministicParameters_inputFormat *, const char*, const char*);

#define soap_read__ns2__DeterministicParameters_inputFormat(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__DeterministicParameters_inputFormat(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum _ns2__DeterministicParameters_inputFormat * SOAP_FMAC4 soap_get__ns2__DeterministicParameters_inputFormat(struct soap*, enum _ns2__DeterministicParameters_inputFormat *, const char*, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#define soap_write_bool(soap, data) ( soap_begin_send(soap) || (soap_serialize_bool(soap, data), 0) || soap_put_bool(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__StatusCode
#define SOAP_TYPE_ns3__StatusCode (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__StatusCode(struct soap*, enum ns3__StatusCode *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__StatusCode(struct soap*, const char*, int, const enum ns3__StatusCode *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns3__StatusCode2s(struct soap*, enum ns3__StatusCode);
SOAP_FMAC3 enum ns3__StatusCode * SOAP_FMAC4 soap_in_ns3__StatusCode(struct soap*, const char*, enum ns3__StatusCode *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns3__StatusCode(struct soap*, const char*, enum ns3__StatusCode *);

#define soap_write_ns3__StatusCode(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__StatusCode(soap, data), 0) || soap_put_ns3__StatusCode(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__StatusCode(struct soap*, const enum ns3__StatusCode *, const char*, const char*);

#define soap_read_ns3__StatusCode(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__StatusCode(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum ns3__StatusCode * SOAP_FMAC4 soap_get_ns3__StatusCode(struct soap*, enum ns3__StatusCode *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__Variable
#define SOAP_TYPE_ns2__Variable (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Variable(struct soap*, enum ns2__Variable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Variable(struct soap*, const char*, int, const enum ns2__Variable *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__Variable2s(struct soap*, enum ns2__Variable);
SOAP_FMAC3 enum ns2__Variable * SOAP_FMAC4 soap_in_ns2__Variable(struct soap*, const char*, enum ns2__Variable *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__Variable(struct soap*, const char*, enum ns2__Variable *);

#define soap_write_ns2__Variable(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__Variable(soap, data), 0) || soap_put_ns2__Variable(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Variable(struct soap*, const enum ns2__Variable *, const char*, const char*);

#define soap_read_ns2__Variable(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__Variable(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum ns2__Variable * SOAP_FMAC4 soap_get_ns2__Variable(struct soap*, enum ns2__Variable *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__Function
#define SOAP_TYPE_ns2__Function (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Function(struct soap*, enum ns2__Function *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Function(struct soap*, const char*, int, const enum ns2__Function *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__Function2s(struct soap*, enum ns2__Function);
SOAP_FMAC3 enum ns2__Function * SOAP_FMAC4 soap_in_ns2__Function(struct soap*, const char*, enum ns2__Function *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__Function(struct soap*, const char*, enum ns2__Function *);

#define soap_write_ns2__Function(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__Function(soap, data), 0) || soap_put_ns2__Function(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Function(struct soap*, const enum ns2__Function *, const char*, const char*);

#define soap_read_ns2__Function(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__Function(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum ns2__Function * SOAP_FMAC4 soap_get_ns2__Function(struct soap*, enum ns2__Function *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__ResourceProperty
#define SOAP_TYPE__ns3__ResourceProperty (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__ResourceProperty(struct soap*, const char*, int, const _ns3__ResourceProperty *, const char*);
SOAP_FMAC3 _ns3__ResourceProperty * SOAP_FMAC4 soap_in__ns3__ResourceProperty(struct soap*, const char*, _ns3__ResourceProperty *, const char*);

#define soap_write__ns3__ResourceProperty(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__ResourceProperty(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__ResourceProperty(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__ResourceProperty * SOAP_FMAC4 soap_get__ns3__ResourceProperty(struct soap*, _ns3__ResourceProperty *, const char*, const char*);

#define soap_new__ns3__ResourceProperty(soap, n) ::soap_instantiate__ns3__ResourceProperty(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__ResourceProperty(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__ResourceProperty * SOAP_FMAC2 soap_instantiate__ns3__ResourceProperty(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__ResourceProperty(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__ServiceFault
#define SOAP_TYPE__ns3__ServiceFault (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__ServiceFault(struct soap*, const char*, int, const _ns3__ServiceFault *, const char*);
SOAP_FMAC3 _ns3__ServiceFault * SOAP_FMAC4 soap_in__ns3__ServiceFault(struct soap*, const char*, _ns3__ServiceFault *, const char*);

#define soap_write__ns3__ServiceFault(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__ServiceFault(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__ServiceFault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__ServiceFault * SOAP_FMAC4 soap_get__ns3__ServiceFault(struct soap*, _ns3__ServiceFault *, const char*, const char*);

#define soap_new__ns3__ServiceFault(soap, n) ::soap_instantiate__ns3__ServiceFault(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__ServiceFault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__ServiceFault * SOAP_FMAC2 soap_instantiate__ns3__ServiceFault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__ServiceFault(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__DeleteSimulationResourceResponse
#define SOAP_TYPE__ns3__DeleteSimulationResourceResponse (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__DeleteSimulationResourceResponse(struct soap*, const char*, int, const _ns3__DeleteSimulationResourceResponse *, const char*);
SOAP_FMAC3 _ns3__DeleteSimulationResourceResponse * SOAP_FMAC4 soap_in__ns3__DeleteSimulationResourceResponse(struct soap*, const char*, _ns3__DeleteSimulationResourceResponse *, const char*);

#define soap_write__ns3__DeleteSimulationResourceResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__DeleteSimulationResourceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__DeleteSimulationResourceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__DeleteSimulationResourceResponse * SOAP_FMAC4 soap_get__ns3__DeleteSimulationResourceResponse(struct soap*, _ns3__DeleteSimulationResourceResponse *, const char*, const char*);

#define soap_new__ns3__DeleteSimulationResourceResponse(soap, n) ::soap_instantiate__ns3__DeleteSimulationResourceResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__DeleteSimulationResourceResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__DeleteSimulationResourceResponse * SOAP_FMAC2 soap_instantiate__ns3__DeleteSimulationResourceResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__DeleteSimulationResourceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__DeleteSimulationResource
#define SOAP_TYPE__ns3__DeleteSimulationResource (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__DeleteSimulationResource(struct soap*, const char*, int, const _ns3__DeleteSimulationResource *, const char*);
SOAP_FMAC3 _ns3__DeleteSimulationResource * SOAP_FMAC4 soap_in__ns3__DeleteSimulationResource(struct soap*, const char*, _ns3__DeleteSimulationResource *, const char*);

#define soap_write__ns3__DeleteSimulationResource(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__DeleteSimulationResource(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__DeleteSimulationResource(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__DeleteSimulationResource * SOAP_FMAC4 soap_get__ns3__DeleteSimulationResource(struct soap*, _ns3__DeleteSimulationResource *, const char*, const char*);

#define soap_new__ns3__DeleteSimulationResource(soap, n) ::soap_instantiate__ns3__DeleteSimulationResource(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__DeleteSimulationResource(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__DeleteSimulationResource * SOAP_FMAC2 soap_instantiate__ns3__DeleteSimulationResource(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__DeleteSimulationResource(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__GetResultResponse
#define SOAP_TYPE__ns3__GetResultResponse (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetResultResponse(struct soap*, const char*, int, const _ns3__GetResultResponse *, const char*);
SOAP_FMAC3 _ns3__GetResultResponse * SOAP_FMAC4 soap_in__ns3__GetResultResponse(struct soap*, const char*, _ns3__GetResultResponse *, const char*);

#define soap_write__ns3__GetResultResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__GetResultResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetResultResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetResultResponse * SOAP_FMAC4 soap_get__ns3__GetResultResponse(struct soap*, _ns3__GetResultResponse *, const char*, const char*);

#define soap_new__ns3__GetResultResponse(soap, n) ::soap_instantiate__ns3__GetResultResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__GetResultResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__GetResultResponse * SOAP_FMAC2 soap_instantiate__ns3__GetResultResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__GetResultResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__GetResult
#define SOAP_TYPE__ns3__GetResult (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetResult(struct soap*, const char*, int, const _ns3__GetResult *, const char*);
SOAP_FMAC3 _ns3__GetResult * SOAP_FMAC4 soap_in__ns3__GetResult(struct soap*, const char*, _ns3__GetResult *, const char*);

#define soap_write__ns3__GetResult(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__GetResult(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetResult * SOAP_FMAC4 soap_get__ns3__GetResult(struct soap*, _ns3__GetResult *, const char*, const char*);

#define soap_new__ns3__GetResult(soap, n) ::soap_instantiate__ns3__GetResult(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__GetResult(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__GetResult * SOAP_FMAC2 soap_instantiate__ns3__GetResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__GetResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__GetSimulatorStatusResponse
#define SOAP_TYPE__ns3__GetSimulatorStatusResponse (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetSimulatorStatusResponse(struct soap*, const char*, int, const _ns3__GetSimulatorStatusResponse *, const char*);
SOAP_FMAC3 _ns3__GetSimulatorStatusResponse * SOAP_FMAC4 soap_in__ns3__GetSimulatorStatusResponse(struct soap*, const char*, _ns3__GetSimulatorStatusResponse *, const char*);

#define soap_write__ns3__GetSimulatorStatusResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__GetSimulatorStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetSimulatorStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetSimulatorStatusResponse * SOAP_FMAC4 soap_get__ns3__GetSimulatorStatusResponse(struct soap*, _ns3__GetSimulatorStatusResponse *, const char*, const char*);

#define soap_new__ns3__GetSimulatorStatusResponse(soap, n) ::soap_instantiate__ns3__GetSimulatorStatusResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__GetSimulatorStatusResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__GetSimulatorStatusResponse * SOAP_FMAC2 soap_instantiate__ns3__GetSimulatorStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__GetSimulatorStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns3__GetSimulatorStatus
#define SOAP_TYPE__ns3__GetSimulatorStatus (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetSimulatorStatus(struct soap*, const char*, int, const _ns3__GetSimulatorStatus *, const char*);
SOAP_FMAC3 _ns3__GetSimulatorStatus * SOAP_FMAC4 soap_in__ns3__GetSimulatorStatus(struct soap*, const char*, _ns3__GetSimulatorStatus *, const char*);

#define soap_write__ns3__GetSimulatorStatus(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns3__GetSimulatorStatus(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetSimulatorStatus(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetSimulatorStatus * SOAP_FMAC4 soap_get__ns3__GetSimulatorStatus(struct soap*, _ns3__GetSimulatorStatus *, const char*, const char*);

#define soap_new__ns3__GetSimulatorStatus(soap, n) ::soap_instantiate__ns3__GetSimulatorStatus(soap, n, NULL, NULL, NULL)


#define soap_delete__ns3__GetSimulatorStatus(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns3__GetSimulatorStatus * SOAP_FMAC2 soap_instantiate__ns3__GetSimulatorStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns3__GetSimulatorStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__OutputResult
#define SOAP_TYPE_ns3__OutputResult (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__OutputResult(struct soap*, const char*, int, const ns3__OutputResult *, const char*);
SOAP_FMAC3 ns3__OutputResult * SOAP_FMAC4 soap_in_ns3__OutputResult(struct soap*, const char*, ns3__OutputResult *, const char*);

#define soap_write_ns3__OutputResult(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns3__OutputResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__OutputResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__OutputResult * SOAP_FMAC4 soap_get_ns3__OutputResult(struct soap*, ns3__OutputResult *, const char*, const char*);

#define soap_new_ns3__OutputResult(soap, n) ::soap_instantiate_ns3__OutputResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__OutputResult(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns3__OutputResult * SOAP_FMAC2 soap_instantiate_ns3__OutputResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__OutputResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__User
#define SOAP_TYPE_ns3__User (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__User(struct soap*, const char*, int, const ns3__User *, const char*);
SOAP_FMAC3 ns3__User * SOAP_FMAC4 soap_in_ns3__User(struct soap*, const char*, ns3__User *, const char*);

#define soap_write_ns3__User(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns3__User(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__User(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__User * SOAP_FMAC4 soap_get_ns3__User(struct soap*, ns3__User *, const char*, const char*);

#define soap_new_ns3__User(soap, n) ::soap_instantiate_ns3__User(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__User(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns3__User * SOAP_FMAC2 soap_instantiate_ns3__User(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__User(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__Transaction
#define SOAP_TYPE_ns3__Transaction (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Transaction(struct soap*, const char*, int, const ns3__Transaction *, const char*);
SOAP_FMAC3 ns3__Transaction * SOAP_FMAC4 soap_in_ns3__Transaction(struct soap*, const char*, ns3__Transaction *, const char*);

#define soap_write_ns3__Transaction(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns3__Transaction(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__Transaction(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__Transaction * SOAP_FMAC4 soap_get_ns3__Transaction(struct soap*, ns3__Transaction *, const char*, const char*);

#define soap_new_ns3__Transaction(soap, n) ::soap_instantiate_ns3__Transaction(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__Transaction(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns3__Transaction * SOAP_FMAC2 soap_instantiate_ns3__Transaction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__Transaction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__Status
#define SOAP_TYPE_ns3__Status (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Status(struct soap*, const char*, int, const ns3__Status *, const char*);
SOAP_FMAC3 ns3__Status * SOAP_FMAC4 soap_in_ns3__Status(struct soap*, const char*, ns3__Status *, const char*);

#define soap_write_ns3__Status(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns3__Status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__Status(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__Status * SOAP_FMAC4 soap_get_ns3__Status(struct soap*, ns3__Status *, const char*, const char*);

#define soap_new_ns3__Status(soap, n) ::soap_instantiate_ns3__Status(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__Status(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns3__Status * SOAP_FMAC2 soap_instantiate_ns3__Status(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__Status(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__StartDeterministicSimulatorResponse
#define SOAP_TYPE__ns2__StartDeterministicSimulatorResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__StartDeterministicSimulatorResponse(struct soap*, const char*, int, const _ns2__StartDeterministicSimulatorResponse *, const char*);
SOAP_FMAC3 _ns2__StartDeterministicSimulatorResponse * SOAP_FMAC4 soap_in__ns2__StartDeterministicSimulatorResponse(struct soap*, const char*, _ns2__StartDeterministicSimulatorResponse *, const char*);

#define soap_write__ns2__StartDeterministicSimulatorResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns2__StartDeterministicSimulatorResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__StartDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__StartDeterministicSimulatorResponse * SOAP_FMAC4 soap_get__ns2__StartDeterministicSimulatorResponse(struct soap*, _ns2__StartDeterministicSimulatorResponse *, const char*, const char*);

#define soap_new__ns2__StartDeterministicSimulatorResponse(soap, n) ::soap_instantiate__ns2__StartDeterministicSimulatorResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__StartDeterministicSimulatorResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__StartDeterministicSimulatorResponse * SOAP_FMAC2 soap_instantiate__ns2__StartDeterministicSimulatorResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__StartDeterministicSimulatorResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__StartDeterministicSimulator
#define SOAP_TYPE__ns2__StartDeterministicSimulator (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__StartDeterministicSimulator(struct soap*, const char*, int, const _ns2__StartDeterministicSimulator *, const char*);
SOAP_FMAC3 _ns2__StartDeterministicSimulator * SOAP_FMAC4 soap_in__ns2__StartDeterministicSimulator(struct soap*, const char*, _ns2__StartDeterministicSimulator *, const char*);

#define soap_write__ns2__StartDeterministicSimulator(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns2__StartDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__StartDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__StartDeterministicSimulator * SOAP_FMAC4 soap_get__ns2__StartDeterministicSimulator(struct soap*, _ns2__StartDeterministicSimulator *, const char*, const char*);

#define soap_new__ns2__StartDeterministicSimulator(soap, n) ::soap_instantiate__ns2__StartDeterministicSimulator(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__StartDeterministicSimulator(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__StartDeterministicSimulator * SOAP_FMAC2 soap_instantiate__ns2__StartDeterministicSimulator(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__StartDeterministicSimulator(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__RunDeterministicSimulatorResponse
#define SOAP_TYPE__ns2__RunDeterministicSimulatorResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__RunDeterministicSimulatorResponse(struct soap*, const char*, int, const _ns2__RunDeterministicSimulatorResponse *, const char*);
SOAP_FMAC3 _ns2__RunDeterministicSimulatorResponse * SOAP_FMAC4 soap_in__ns2__RunDeterministicSimulatorResponse(struct soap*, const char*, _ns2__RunDeterministicSimulatorResponse *, const char*);

#define soap_write__ns2__RunDeterministicSimulatorResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns2__RunDeterministicSimulatorResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__RunDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__RunDeterministicSimulatorResponse * SOAP_FMAC4 soap_get__ns2__RunDeterministicSimulatorResponse(struct soap*, _ns2__RunDeterministicSimulatorResponse *, const char*, const char*);

#define soap_new__ns2__RunDeterministicSimulatorResponse(soap, n) ::soap_instantiate__ns2__RunDeterministicSimulatorResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__RunDeterministicSimulatorResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__RunDeterministicSimulatorResponse * SOAP_FMAC2 soap_instantiate__ns2__RunDeterministicSimulatorResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__RunDeterministicSimulatorResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__RunDeterministicSimulator
#define SOAP_TYPE__ns2__RunDeterministicSimulator (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__RunDeterministicSimulator(struct soap*, const char*, int, const _ns2__RunDeterministicSimulator *, const char*);
SOAP_FMAC3 _ns2__RunDeterministicSimulator * SOAP_FMAC4 soap_in__ns2__RunDeterministicSimulator(struct soap*, const char*, _ns2__RunDeterministicSimulator *, const char*);

#define soap_write__ns2__RunDeterministicSimulator(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns2__RunDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__RunDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__RunDeterministicSimulator * SOAP_FMAC4 soap_get__ns2__RunDeterministicSimulator(struct soap*, _ns2__RunDeterministicSimulator *, const char*, const char*);

#define soap_new__ns2__RunDeterministicSimulator(soap, n) ::soap_instantiate__ns2__RunDeterministicSimulator(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__RunDeterministicSimulator(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__RunDeterministicSimulator * SOAP_FMAC2 soap_instantiate__ns2__RunDeterministicSimulator(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__RunDeterministicSimulator(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__SensitivityParameters
#define SOAP_TYPE_ns2__SensitivityParameters (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SensitivityParameters(struct soap*, const char*, int, const ns2__SensitivityParameters *, const char*);
SOAP_FMAC3 ns2__SensitivityParameters * SOAP_FMAC4 soap_in_ns2__SensitivityParameters(struct soap*, const char*, ns2__SensitivityParameters *, const char*);

#define soap_write_ns2__SensitivityParameters(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns2__SensitivityParameters(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__SensitivityParameters(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns2__SensitivityParameters * SOAP_FMAC4 soap_get_ns2__SensitivityParameters(struct soap*, ns2__SensitivityParameters *, const char*, const char*);

#define soap_new_ns2__SensitivityParameters(soap, n) ::soap_instantiate_ns2__SensitivityParameters(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__SensitivityParameters(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__SensitivityParameters * SOAP_FMAC2 soap_instantiate_ns2__SensitivityParameters(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__SensitivityParameters(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__DeterministicParameters
#define SOAP_TYPE_ns2__DeterministicParameters (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DeterministicParameters(struct soap*, const char*, int, const ns2__DeterministicParameters *, const char*);
SOAP_FMAC3 ns2__DeterministicParameters * SOAP_FMAC4 soap_in_ns2__DeterministicParameters(struct soap*, const char*, ns2__DeterministicParameters *, const char*);

#define soap_write_ns2__DeterministicParameters(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns2__DeterministicParameters(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DeterministicParameters(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns2__DeterministicParameters * SOAP_FMAC4 soap_get_ns2__DeterministicParameters(struct soap*, ns2__DeterministicParameters *, const char*, const char*);

#define soap_new_ns2__DeterministicParameters(soap, n) ::soap_instantiate_ns2__DeterministicParameters(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__DeterministicParameters(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__DeterministicParameters * SOAP_FMAC2 soap_instantiate_ns2__DeterministicParameters(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__DeterministicParameters(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (10)
#endif

#define soap_default_xsd__nonNegativeInteger(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__nonNegativeInteger(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger(struct soap*, const char*, std::string*, const char*);

#define soap_write_xsd__nonNegativeInteger(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__nonNegativeInteger(struct soap*, const std::string *, const char*, const char*);

#define soap_read_xsd__nonNegativeInteger(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__nonNegativeInteger(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__nonNegativeInteger(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__nonNegativeInteger(soap, n) ::soap_instantiate_xsd__nonNegativeInteger(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__nonNegativeInteger(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__nonNegativeInteger soap_instantiate_std__string


#define soap_copy_xsd__nonNegativeInteger soap_copy_std__string

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (9)
#endif

#define soap_default_xsd__integer(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__integer(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, std::string*, const char*);

#define soap_write_xsd__integer(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, const std::string *, const char*, const char*);

#define soap_read_xsd__integer(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__integer(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__integer(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__integer(soap, n) ::soap_instantiate_xsd__integer(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__integer(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__integer soap_instantiate_std__string


#define soap_copy_xsd__integer soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) ::soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) ::soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) ::soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) ::soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) ::soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__deleteSimulationResource
#define SOAP_TYPE___ns1__deleteSimulationResource (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__deleteSimulationResource(struct soap*, struct __ns1__deleteSimulationResource *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__deleteSimulationResource(struct soap*, const struct __ns1__deleteSimulationResource *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__deleteSimulationResource(struct soap*, const char*, int, const struct __ns1__deleteSimulationResource *, const char*);
SOAP_FMAC3 struct __ns1__deleteSimulationResource * SOAP_FMAC4 soap_in___ns1__deleteSimulationResource(struct soap*, const char*, struct __ns1__deleteSimulationResource *, const char*);

#define soap_write___ns1__deleteSimulationResource(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__deleteSimulationResource(soap, data), 0) || soap_put___ns1__deleteSimulationResource(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__deleteSimulationResource(struct soap*, const struct __ns1__deleteSimulationResource *, const char*, const char*);

#define soap_read___ns1__deleteSimulationResource(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__deleteSimulationResource(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__deleteSimulationResource * SOAP_FMAC4 soap_get___ns1__deleteSimulationResource(struct soap*, struct __ns1__deleteSimulationResource *, const char*, const char*);

#define soap_new___ns1__deleteSimulationResource(soap, n) ::soap_instantiate___ns1__deleteSimulationResource(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__deleteSimulationResource(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__deleteSimulationResource * SOAP_FMAC2 soap_instantiate___ns1__deleteSimulationResource(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__deleteSimulationResource(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getResult
#define SOAP_TYPE___ns1__getResult (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getResult(struct soap*, struct __ns1__getResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getResult(struct soap*, const struct __ns1__getResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getResult(struct soap*, const char*, int, const struct __ns1__getResult *, const char*);
SOAP_FMAC3 struct __ns1__getResult * SOAP_FMAC4 soap_in___ns1__getResult(struct soap*, const char*, struct __ns1__getResult *, const char*);

#define soap_write___ns1__getResult(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__getResult(soap, data), 0) || soap_put___ns1__getResult(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getResult(struct soap*, const struct __ns1__getResult *, const char*, const char*);

#define soap_read___ns1__getResult(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__getResult * SOAP_FMAC4 soap_get___ns1__getResult(struct soap*, struct __ns1__getResult *, const char*, const char*);

#define soap_new___ns1__getResult(soap, n) ::soap_instantiate___ns1__getResult(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__getResult(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__getResult * SOAP_FMAC2 soap_instantiate___ns1__getResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSimulatorStatus
#define SOAP_TYPE___ns1__getSimulatorStatus (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSimulatorStatus(struct soap*, struct __ns1__getSimulatorStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSimulatorStatus(struct soap*, const struct __ns1__getSimulatorStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSimulatorStatus(struct soap*, const char*, int, const struct __ns1__getSimulatorStatus *, const char*);
SOAP_FMAC3 struct __ns1__getSimulatorStatus * SOAP_FMAC4 soap_in___ns1__getSimulatorStatus(struct soap*, const char*, struct __ns1__getSimulatorStatus *, const char*);

#define soap_write___ns1__getSimulatorStatus(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__getSimulatorStatus(soap, data), 0) || soap_put___ns1__getSimulatorStatus(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSimulatorStatus(struct soap*, const struct __ns1__getSimulatorStatus *, const char*, const char*);

#define soap_read___ns1__getSimulatorStatus(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSimulatorStatus(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__getSimulatorStatus * SOAP_FMAC4 soap_get___ns1__getSimulatorStatus(struct soap*, struct __ns1__getSimulatorStatus *, const char*, const char*);

#define soap_new___ns1__getSimulatorStatus(soap, n) ::soap_instantiate___ns1__getSimulatorStatus(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__getSimulatorStatus(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__getSimulatorStatus * SOAP_FMAC2 soap_instantiate___ns1__getSimulatorStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSimulatorStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__startDeterministicSimulator
#define SOAP_TYPE___ns1__startDeterministicSimulator (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__startDeterministicSimulator(struct soap*, struct __ns1__startDeterministicSimulator *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__startDeterministicSimulator(struct soap*, const struct __ns1__startDeterministicSimulator *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__startDeterministicSimulator(struct soap*, const char*, int, const struct __ns1__startDeterministicSimulator *, const char*);
SOAP_FMAC3 struct __ns1__startDeterministicSimulator * SOAP_FMAC4 soap_in___ns1__startDeterministicSimulator(struct soap*, const char*, struct __ns1__startDeterministicSimulator *, const char*);

#define soap_write___ns1__startDeterministicSimulator(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__startDeterministicSimulator(soap, data), 0) || soap_put___ns1__startDeterministicSimulator(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__startDeterministicSimulator(struct soap*, const struct __ns1__startDeterministicSimulator *, const char*, const char*);

#define soap_read___ns1__startDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__startDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__startDeterministicSimulator * SOAP_FMAC4 soap_get___ns1__startDeterministicSimulator(struct soap*, struct __ns1__startDeterministicSimulator *, const char*, const char*);

#define soap_new___ns1__startDeterministicSimulator(soap, n) ::soap_instantiate___ns1__startDeterministicSimulator(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__startDeterministicSimulator(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__startDeterministicSimulator * SOAP_FMAC2 soap_instantiate___ns1__startDeterministicSimulator(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__startDeterministicSimulator(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__runDeterministicSimulator
#define SOAP_TYPE___ns1__runDeterministicSimulator (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__runDeterministicSimulator(struct soap*, struct __ns1__runDeterministicSimulator *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__runDeterministicSimulator(struct soap*, const struct __ns1__runDeterministicSimulator *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__runDeterministicSimulator(struct soap*, const char*, int, const struct __ns1__runDeterministicSimulator *, const char*);
SOAP_FMAC3 struct __ns1__runDeterministicSimulator * SOAP_FMAC4 soap_in___ns1__runDeterministicSimulator(struct soap*, const char*, struct __ns1__runDeterministicSimulator *, const char*);

#define soap_write___ns1__runDeterministicSimulator(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__runDeterministicSimulator(soap, data), 0) || soap_put___ns1__runDeterministicSimulator(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__runDeterministicSimulator(struct soap*, const struct __ns1__runDeterministicSimulator *, const char*, const char*);

#define soap_read___ns1__runDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__runDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__runDeterministicSimulator * SOAP_FMAC4 soap_get___ns1__runDeterministicSimulator(struct soap*, struct __ns1__runDeterministicSimulator *, const char*, const char*);

#define soap_new___ns1__runDeterministicSimulator(soap, n) ::soap_instantiate___ns1__runDeterministicSimulator(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__runDeterministicSimulator(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__runDeterministicSimulator * SOAP_FMAC2 soap_instantiate___ns1__runDeterministicSimulator(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__runDeterministicSimulator(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) ::soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE__ns2__union_DeterministicParameters
#define SOAP_TYPE__ns2__union_DeterministicParameters (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns2__union_DeterministicParameters(struct soap*, int, const union _ns2__union_DeterministicParameters *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__union_DeterministicParameters(struct soap*, int, const union _ns2__union_DeterministicParameters *);
SOAP_FMAC3 union _ns2__union_DeterministicParameters * SOAP_FMAC4 soap_in__ns2__union_DeterministicParameters(struct soap*, int*, union _ns2__union_DeterministicParameters *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns3__DeleteSimulationResourceResponse
#define SOAP_TYPE_PointerTo_ns3__DeleteSimulationResourceResponse (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__DeleteSimulationResourceResponse(struct soap*, _ns3__DeleteSimulationResourceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__DeleteSimulationResourceResponse(struct soap*, const char *, int, _ns3__DeleteSimulationResourceResponse *const*, const char *);
SOAP_FMAC3 _ns3__DeleteSimulationResourceResponse ** SOAP_FMAC4 soap_in_PointerTo_ns3__DeleteSimulationResourceResponse(struct soap*, const char*, _ns3__DeleteSimulationResourceResponse **, const char*);

#define soap_write_PointerTo_ns3__DeleteSimulationResourceResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__DeleteSimulationResourceResponse(soap, data), 0) || soap_put_PointerTo_ns3__DeleteSimulationResourceResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__DeleteSimulationResourceResponse(struct soap*, _ns3__DeleteSimulationResourceResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__DeleteSimulationResourceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__DeleteSimulationResourceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__DeleteSimulationResourceResponse ** SOAP_FMAC4 soap_get_PointerTo_ns3__DeleteSimulationResourceResponse(struct soap*, _ns3__DeleteSimulationResourceResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__DeleteSimulationResource
#define SOAP_TYPE_PointerTo_ns3__DeleteSimulationResource (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__DeleteSimulationResource(struct soap*, _ns3__DeleteSimulationResource *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__DeleteSimulationResource(struct soap*, const char *, int, _ns3__DeleteSimulationResource *const*, const char *);
SOAP_FMAC3 _ns3__DeleteSimulationResource ** SOAP_FMAC4 soap_in_PointerTo_ns3__DeleteSimulationResource(struct soap*, const char*, _ns3__DeleteSimulationResource **, const char*);

#define soap_write_PointerTo_ns3__DeleteSimulationResource(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__DeleteSimulationResource(soap, data), 0) || soap_put_PointerTo_ns3__DeleteSimulationResource(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__DeleteSimulationResource(struct soap*, _ns3__DeleteSimulationResource *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__DeleteSimulationResource(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__DeleteSimulationResource(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__DeleteSimulationResource ** SOAP_FMAC4 soap_get_PointerTo_ns3__DeleteSimulationResource(struct soap*, _ns3__DeleteSimulationResource **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetResultResponse
#define SOAP_TYPE_PointerTo_ns3__GetResultResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetResultResponse(struct soap*, _ns3__GetResultResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetResultResponse(struct soap*, const char *, int, _ns3__GetResultResponse *const*, const char *);
SOAP_FMAC3 _ns3__GetResultResponse ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetResultResponse(struct soap*, const char*, _ns3__GetResultResponse **, const char*);

#define soap_write_PointerTo_ns3__GetResultResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetResultResponse(soap, data), 0) || soap_put_PointerTo_ns3__GetResultResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetResultResponse(struct soap*, _ns3__GetResultResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetResultResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetResultResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetResultResponse ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetResultResponse(struct soap*, _ns3__GetResultResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetResult
#define SOAP_TYPE_PointerTo_ns3__GetResult (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetResult(struct soap*, _ns3__GetResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetResult(struct soap*, const char *, int, _ns3__GetResult *const*, const char *);
SOAP_FMAC3 _ns3__GetResult ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetResult(struct soap*, const char*, _ns3__GetResult **, const char*);

#define soap_write_PointerTo_ns3__GetResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetResult(soap, data), 0) || soap_put_PointerTo_ns3__GetResult(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetResult(struct soap*, _ns3__GetResult *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetResult ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetResult(struct soap*, _ns3__GetResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetSimulatorStatusResponse
#define SOAP_TYPE_PointerTo_ns3__GetSimulatorStatusResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetSimulatorStatusResponse(struct soap*, _ns3__GetSimulatorStatusResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetSimulatorStatusResponse(struct soap*, const char *, int, _ns3__GetSimulatorStatusResponse *const*, const char *);
SOAP_FMAC3 _ns3__GetSimulatorStatusResponse ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetSimulatorStatusResponse(struct soap*, const char*, _ns3__GetSimulatorStatusResponse **, const char*);

#define soap_write_PointerTo_ns3__GetSimulatorStatusResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetSimulatorStatusResponse(soap, data), 0) || soap_put_PointerTo_ns3__GetSimulatorStatusResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetSimulatorStatusResponse(struct soap*, _ns3__GetSimulatorStatusResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetSimulatorStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetSimulatorStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetSimulatorStatusResponse ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetSimulatorStatusResponse(struct soap*, _ns3__GetSimulatorStatusResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetSimulatorStatus
#define SOAP_TYPE_PointerTo_ns3__GetSimulatorStatus (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetSimulatorStatus(struct soap*, _ns3__GetSimulatorStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetSimulatorStatus(struct soap*, const char *, int, _ns3__GetSimulatorStatus *const*, const char *);
SOAP_FMAC3 _ns3__GetSimulatorStatus ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetSimulatorStatus(struct soap*, const char*, _ns3__GetSimulatorStatus **, const char*);

#define soap_write_PointerTo_ns3__GetSimulatorStatus(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetSimulatorStatus(soap, data), 0) || soap_put_PointerTo_ns3__GetSimulatorStatus(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetSimulatorStatus(struct soap*, _ns3__GetSimulatorStatus *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetSimulatorStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetSimulatorStatus(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__GetSimulatorStatus ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetSimulatorStatus(struct soap*, _ns3__GetSimulatorStatus **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__StartDeterministicSimulatorResponse
#define SOAP_TYPE_PointerTo_ns2__StartDeterministicSimulatorResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__StartDeterministicSimulatorResponse(struct soap*, _ns2__StartDeterministicSimulatorResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__StartDeterministicSimulatorResponse(struct soap*, const char *, int, _ns2__StartDeterministicSimulatorResponse *const*, const char *);
SOAP_FMAC3 _ns2__StartDeterministicSimulatorResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__StartDeterministicSimulatorResponse(struct soap*, const char*, _ns2__StartDeterministicSimulatorResponse **, const char*);

#define soap_write_PointerTo_ns2__StartDeterministicSimulatorResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__StartDeterministicSimulatorResponse(soap, data), 0) || soap_put_PointerTo_ns2__StartDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__StartDeterministicSimulatorResponse(struct soap*, _ns2__StartDeterministicSimulatorResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns2__StartDeterministicSimulatorResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__StartDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__StartDeterministicSimulatorResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__StartDeterministicSimulatorResponse(struct soap*, _ns2__StartDeterministicSimulatorResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__StartDeterministicSimulator
#define SOAP_TYPE_PointerTo_ns2__StartDeterministicSimulator (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__StartDeterministicSimulator(struct soap*, _ns2__StartDeterministicSimulator *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__StartDeterministicSimulator(struct soap*, const char *, int, _ns2__StartDeterministicSimulator *const*, const char *);
SOAP_FMAC3 _ns2__StartDeterministicSimulator ** SOAP_FMAC4 soap_in_PointerTo_ns2__StartDeterministicSimulator(struct soap*, const char*, _ns2__StartDeterministicSimulator **, const char*);

#define soap_write_PointerTo_ns2__StartDeterministicSimulator(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__StartDeterministicSimulator(soap, data), 0) || soap_put_PointerTo_ns2__StartDeterministicSimulator(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__StartDeterministicSimulator(struct soap*, _ns2__StartDeterministicSimulator *const*, const char*, const char*);

#define soap_read_PointerTo_ns2__StartDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__StartDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__StartDeterministicSimulator ** SOAP_FMAC4 soap_get_PointerTo_ns2__StartDeterministicSimulator(struct soap*, _ns2__StartDeterministicSimulator **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__RunDeterministicSimulatorResponse
#define SOAP_TYPE_PointerTo_ns2__RunDeterministicSimulatorResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__RunDeterministicSimulatorResponse(struct soap*, _ns2__RunDeterministicSimulatorResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__RunDeterministicSimulatorResponse(struct soap*, const char *, int, _ns2__RunDeterministicSimulatorResponse *const*, const char *);
SOAP_FMAC3 _ns2__RunDeterministicSimulatorResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__RunDeterministicSimulatorResponse(struct soap*, const char*, _ns2__RunDeterministicSimulatorResponse **, const char*);

#define soap_write_PointerTo_ns2__RunDeterministicSimulatorResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__RunDeterministicSimulatorResponse(soap, data), 0) || soap_put_PointerTo_ns2__RunDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__RunDeterministicSimulatorResponse(struct soap*, _ns2__RunDeterministicSimulatorResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns2__RunDeterministicSimulatorResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__RunDeterministicSimulatorResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__RunDeterministicSimulatorResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__RunDeterministicSimulatorResponse(struct soap*, _ns2__RunDeterministicSimulatorResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__RunDeterministicSimulator
#define SOAP_TYPE_PointerTo_ns2__RunDeterministicSimulator (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__RunDeterministicSimulator(struct soap*, _ns2__RunDeterministicSimulator *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__RunDeterministicSimulator(struct soap*, const char *, int, _ns2__RunDeterministicSimulator *const*, const char *);
SOAP_FMAC3 _ns2__RunDeterministicSimulator ** SOAP_FMAC4 soap_in_PointerTo_ns2__RunDeterministicSimulator(struct soap*, const char*, _ns2__RunDeterministicSimulator **, const char*);

#define soap_write_PointerTo_ns2__RunDeterministicSimulator(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__RunDeterministicSimulator(soap, data), 0) || soap_put_PointerTo_ns2__RunDeterministicSimulator(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__RunDeterministicSimulator(struct soap*, _ns2__RunDeterministicSimulator *const*, const char*, const char*);

#define soap_read_PointerTo_ns2__RunDeterministicSimulator(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__RunDeterministicSimulator(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns2__RunDeterministicSimulator ** SOAP_FMAC4 soap_get_PointerTo_ns2__RunDeterministicSimulator(struct soap*, _ns2__RunDeterministicSimulator **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__ServiceFault
#define SOAP_TYPE_PointerTo_ns3__ServiceFault (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__ServiceFault(struct soap*, _ns3__ServiceFault *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__ServiceFault(struct soap*, const char *, int, _ns3__ServiceFault *const*, const char *);
SOAP_FMAC3 _ns3__ServiceFault ** SOAP_FMAC4 soap_in_PointerTo_ns3__ServiceFault(struct soap*, const char*, _ns3__ServiceFault **, const char*);

#define soap_write_PointerTo_ns3__ServiceFault(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__ServiceFault(soap, data), 0) || soap_put_PointerTo_ns3__ServiceFault(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__ServiceFault(struct soap*, _ns3__ServiceFault *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__ServiceFault(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__ServiceFault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns3__ServiceFault ** SOAP_FMAC4 soap_get_PointerTo_ns3__ServiceFault(struct soap*, _ns3__ServiceFault **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__Status
#define SOAP_TYPE_PointerTons3__Status (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__Status(struct soap*, ns3__Status *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__Status(struct soap*, const char *, int, ns3__Status *const*, const char *);
SOAP_FMAC3 ns3__Status ** SOAP_FMAC4 soap_in_PointerTons3__Status(struct soap*, const char*, ns3__Status **, const char*);

#define soap_write_PointerTons3__Status(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__Status(soap, data), 0) || soap_put_PointerTons3__Status(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__Status(struct soap*, ns3__Status *const*, const char*, const char*);

#define soap_read_PointerTons3__Status(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__Status(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__Status ** SOAP_FMAC4 soap_get_PointerTons3__Status(struct soap*, ns3__Status **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__User
#define SOAP_TYPE_PointerTons3__User (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__User(struct soap*, ns3__User *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__User(struct soap*, const char *, int, ns3__User *const*, const char *);
SOAP_FMAC3 ns3__User ** SOAP_FMAC4 soap_in_PointerTons3__User(struct soap*, const char*, ns3__User **, const char*);

#define soap_write_PointerTons3__User(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__User(soap, data), 0) || soap_put_PointerTons3__User(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__User(struct soap*, ns3__User *const*, const char*, const char*);

#define soap_read_PointerTons3__User(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__User(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__User ** SOAP_FMAC4 soap_get_PointerTons3__User(struct soap*, ns3__User **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__OutputResult
#define SOAP_TYPE_PointerTons3__OutputResult (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__OutputResult(struct soap*, ns3__OutputResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__OutputResult(struct soap*, const char *, int, ns3__OutputResult *const*, const char *);
SOAP_FMAC3 ns3__OutputResult ** SOAP_FMAC4 soap_in_PointerTons3__OutputResult(struct soap*, const char*, ns3__OutputResult **, const char*);

#define soap_write_PointerTons3__OutputResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__OutputResult(soap, data), 0) || soap_put_PointerTons3__OutputResult(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__OutputResult(struct soap*, ns3__OutputResult *const*, const char*, const char*);

#define soap_read_PointerTons3__OutputResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__OutputResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns3__OutputResult ** SOAP_FMAC4 soap_get_PointerTons3__OutputResult(struct soap*, ns3__OutputResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__DeterministicParameters
#define SOAP_TYPE_PointerTons2__DeterministicParameters (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__DeterministicParameters(struct soap*, ns2__DeterministicParameters *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__DeterministicParameters(struct soap*, const char *, int, ns2__DeterministicParameters *const*, const char *);
SOAP_FMAC3 ns2__DeterministicParameters ** SOAP_FMAC4 soap_in_PointerTons2__DeterministicParameters(struct soap*, const char*, ns2__DeterministicParameters **, const char*);

#define soap_write_PointerTons2__DeterministicParameters(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__DeterministicParameters(soap, data), 0) || soap_put_PointerTons2__DeterministicParameters(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__DeterministicParameters(struct soap*, ns2__DeterministicParameters *const*, const char*, const char*);

#define soap_read_PointerTons2__DeterministicParameters(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__DeterministicParameters(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns2__DeterministicParameters ** SOAP_FMAC4 soap_get_PointerTons2__DeterministicParameters(struct soap*, ns2__DeterministicParameters **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#define soap_write_PointerTostd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data), 0) || soap_put_PointerTostd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__SensitivityParameters
#define SOAP_TYPE_PointerTons2__SensitivityParameters (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SensitivityParameters(struct soap*, ns2__SensitivityParameters *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SensitivityParameters(struct soap*, const char *, int, ns2__SensitivityParameters *const*, const char *);
SOAP_FMAC3 ns2__SensitivityParameters ** SOAP_FMAC4 soap_in_PointerTons2__SensitivityParameters(struct soap*, const char*, ns2__SensitivityParameters **, const char*);

#define soap_write_PointerTons2__SensitivityParameters(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__SensitivityParameters(soap, data), 0) || soap_put_PointerTons2__SensitivityParameters(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SensitivityParameters(struct soap*, ns2__SensitivityParameters *const*, const char*, const char*);

#define soap_read_PointerTons2__SensitivityParameters(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__SensitivityParameters(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns2__SensitivityParameters ** SOAP_FMAC4 soap_get_PointerTons2__SensitivityParameters(struct soap*, ns2__SensitivityParameters **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
